finals = {
    'a': "as in 'father'",
    'o': "as in 'awe', 'all', 'got'",
    'e': "similar to 'uh' in 'duh' or 'oo' in 'look'",
    'i (1)': "as in 'zit', 'sit",
    'i (2)': "as in 'shirt'",
    'er': "as in 'teacher'",
    'ai': "as in 'eye'",
    'ei': "as in 'bay', 'pay'",
    'ao': "as in 'ow', 'meow'",
    'ou': "as in 'so'",
    'an': "(I think?) like British-accented 'Anne' (not like 'yawn' or American 'Anne')",
    'en': "as in 'ten', 'taken'",
    'ang': "as 'a' in 'father' + 'ng' in 'song'",
    'eng': "as 'uh' in 'duh' + 'ng' (so like 'dung'?) (Northern: like 'rung')",
    'ong': "as in 'song' (or is it 'oo' like 'boo' + 'eng' like 'dung'?)",
    'i (3)': "as in 'bee' or 'see'",
    'ia': "as 'ee' in 'bee' + 'a' in 'father'",
    'iao': "as 'ee' in 'bee' + 'ow' in 'cow'",
    'ie': "as 'ee' in 'bee' + 'e' in 'yet'",
    'iu': "as 'ee' in 'bee' + 'o' in 'so'",
    'ian': "as in 'yen' (or is it 'i' like 'bee' + 'an' like British 'Anne'?)",
    'in': "as in 'teen', 'preen'",
    'iang': "(?) 'i' like 'bee' + fancy 'angst'?",
    'ing': "(?) 'ee-uhng'",
    'iong': "ü + ong (like 'song'? or is it 'oo' like 'boo' + 'eng' like 'dung'?)",
    'u': "as in 'boo', 'who'",
    'ua': "as in 'boo', 'who' + 'a' in 'father'",
    'uo': "like 'wall'?",
    'uai': "as in 'boo', 'who' + English 'eye'",
    'ui': "as in 'boo', 'who' + 'at' in 'bay'",
    'uan': "like 'wax' but 'n' instead of 'x' sound?",
    'un': "as 'oo' in 'boo' or 'o' in 'who' + 'en' in 'taken' or 'ten'",
    'uang': "as 'oo' in 'boo' or 'o' in 'who' + 'a' in 'father' + 'ng' in 'song'",
    'ueng': "as 'oo' in 'boo' or 'o' in 'who' + 'ung' in 'dung'",
    'ü': "(unlike English) like 'ee' in 'cheese' but with rounded lips",
    'üe': "(unlike English) like 'ee' in 'cheese' but with rounded lips + 'e' in 'yet'",
    'üan': "(unlike English) like 'ee' in 'cheese' but with rounded lips + British 'Anne'",
    'ün': "(unlike English) like 'ee' in 'cheese' but with rounded lips + 'en' in 'taken', 'ten'",
}
