finals = {
    'iang': 'fill me in',
    'eng': 'fill me in',
    'a': 'fill me in',
    'eng': 'fill me in',
    'uo': 'fill me in',
    'iang': 'fill me in',
    'ü': 'fill me in',
    'i (2)': 'fill me in',
    'ai': 'fill me in',
    'uang': 'fill me in',
    'ao': 'fill me in',
    'ing': 'fill me in',
    'ou': 'fill me in',
    'ei': 'fill me in',
    'u': 'fill me in',
    'ui': 'fill me in',
    'ong': 'fill me in',
    'iu': 'fill me in',
    'i': 'fill me in',
    'e': 'fill me in',
    'iao': 'fill me in',
    'u': 'fill me in',
    'en': 'fill me in',
    'u': 'fill me in',
    'an': 'fill me in',
    'a': 'fill me in',
    'uang': 'fill me in',
    'ao': 'fill me in',
    'üan': 'fill me in',
    'eng': 'fill me in',
    'in': 'fill me in',
    'ü': 'fill me in'
}
