initials = {
    None: 'fill me in',
    'b': 'fill me in',
    'p': 'fill me in',
    'm': 'fill me in',
    'f': 'fill me in',
    'd': 'fill me in',
    't': 'fill me in',
    'n': 'fill me in',
    'l': 'fill me in',
    'g': 'fill me in',
    'k': 'fill me in',
    'h': 'fill me in',
    'z': 'fill me in',
    'c': 'fill me in',
    's': 'fill me in',
    'zh': 'fill me in',
    'ch': 'fill me in',
    'sh': 'fill me in',
    'r': 'fill me in',
    'j': 'fill me in',
    'q': 'fill me in',
    'x': 'fill me in'
}
